@startuml Income

title Диаграмма активности

start

-> Авторизированный пользователь;
:Получить данные о таблице доходов;

if (Сотрудник) 
    -> Фотограф;
    ' :Выбрать период, за который\nнужно посмотреть информацию;
    :Просмотреть информацию о доходах\nиз таблицы "Доходы фотографов";
else 
    -> Администратор;
    ' :Выбрать период, за который\nнужно посмотреть информацию;
    :Просмотреть информацию о доходах\nиз таблицы "Доходы администраторов ";
endif

stop

@enduml
