@startuml
title "SmileFoto"

start

:Начало рабочего дня;
repeat 
  :Фотографы работают на склонах;
  :Фотографы передают SD-карты с фотографиями администраторам;
  :Администратор загружает фотографии на компьютер;
  :Сортировка и распределение фотографий по папкам;

  :Клиенты просматривают фотографии на мониторах;

  :Клиент выбирает фотографии и товары;
  :Администратор записывает выбранные фото и товары;

  :Администратор отправляет запрос на удаленный сервер;
  :Сервер отправляет SMS с логином и паролем клиенту;
repeat while (Рабочий день не закончен)

:Подсчет выручки;
:Составление отчета по проданным товарам и фотографиям;
:Отправка информации менеджеру;

:Конец рабочего дня;

stop
@enduml
