@startuml final

title "Диаграмма состояний"

[*] --> Заказ : Покупатель совершил заказ
Заказ --> Обработка : Администратор получает данные заказа
Обработка --> Генерация : Администратор заполняет форму\n отправки данных для сервера
Генерация --> Данные :  Отправка логина и пароля покупателю
Данные --> Авторизация : Пользователь авторизуется в системе

Авторизация --> Успех : Успешная авторизация пользователя
Успех -> [*]

Авторизация --> Отклонено : Покупатель указал неверные\n данные логина или пароля
Отклонено --> Авторизация : Повторная попытка авторизации
Отклонено --> Выход : Покупатель закрывает\n окно авторизации
Выход -> [*]

@enduml